stages:
  prepare_data:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    outs:
    - df_test_.csv
    - df_train_.csv
  modeling:
    cmd: python modeling.py
    deps:
    - modeling.py
    - df_test_.csv
    - df_train_.csv
    outs:
    - DecisionTreeRegressor_model.pkl
    - Lasso_model.pkl 
    - LinearRegression_model.pkl
    - polyreg_model.pkl
    - RandomForestRegressor.pkl

  evaluate:
    cmd: python evaluate.py
    deps:
    - evaluate.py

    outs:
    - result_export.png  
    
    metrics:
    - export.json:
        cache: false