stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    outs:
    - df_test_.csv
    - df_train_.csv
  modeling:
    cmd: python src/modeling.py
    deps:
    - src/modeling.py
    outs:
    - DecisionTreeRegressor_model.pkl
    - Lasso_model.pkl 
    - LinearRegression_model.pkl
    - polyreg_model.pkl
    - RandomForestRegressor.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py

    
    metrics:
    - export.json:
        cache: false