name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 

       
          echo "oky raed -------"
          echo "oky raed 2 -------"
          
          dvc metrics diff master show >> report.md
          cat metrics.json >> report.md
         
          echo "## Validating results by region" >> report.md
          cml-publish by_region.png --md >> report.md


          cml-send-comment report.md

    
